name: markets
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.21+22
# version: 1.0.24+25

analyzer:
  enable-experiment:
    - non-nullable

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  package_info: ^2.0.2
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.0
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  path: ^1.7.0
  quantupi:
  sqflite: ^2.0.2
  path_provider: ^2.0.8
  shared_preferences: ^2.0.12
  mobx: ^2.0.6+1
  jiffy:
  flutter_switch: ^0.3.2
  flutter_mobx: ^2.0.3+2
  flutter_inappwebview: ^5.4.3+7
  shimmer: ^2.0.0
  razorpay_flutter_customui: 1.3.3
  local_auth: ^2.1.5
  lottie: ^2.2.0
  bubble_tab_indicator: ^0.1.4
  sqflite_common_ffi: ^2.1.0+1
  sqlite3_flutter_libs: ^0.5.3
  mask_text_input_formatter: ^2.0.0
  http: ^0.13.4
#  url_launcher: ^6.0.18
  flutter_local_notifications:
  native_screenshot: ^1.0.0
  share: ^2.0.4
  crypto: ^3.0.1
  firebase_core:
  firebase_crashlytics:
  rxdart: ^0.27.3
  flutter_svg:
  device_apps: ^2.1.1
  external_app_launcher: ^3.1.0
  webview_flutter: ^4.0.5
  device_info_plus: ^8.1.0
  dotted_line:
  flutter_time_picker_spinner:
  tutorial_coach_mark: ^1.2.3
  font_awesome_flutter: ^10.4.0
  flutter_html:
  trust_fall:
    git:
      url: https://github.com/thanhit93/trust_fall.git
      ref: null-safety
  charset_converter: ^2.0.0
  flutter_overboard: ^3.0.0
  # ssl_pinning_plugin: ^1.1.0
  fl_chart: ^0.61.0
  permission_handler:
  firebase_analytics:
  googleapis: ^10.1.0
  android_play_install_referrer: ^0.2.1
  instant: ^0.4.1
  flutter_native_timezone: ^2.0.0
  uuid: ^3.0.5
  dio:
  pin_code_fields:
#  firebase_dynamic_links: ^2.0.11
  # connectivity_plus:
  firebase_messaging: ^14.2.5
  store_redirect:
  carousel_slider: ^4.2.1
  flutter_xlider: ^3.4.0
  flutter_pdfview: ^1.2.2
  launch_review: ^3.0.1
  appsflyer_sdk: ^6.5.2+2
  advertising_id: ^2.3.0
  encrypt: ^5.0.1
  platform_device_id: ^1.0.1
  alice:
  syncfusion_flutter_gauges: ^20.4.51
  readmore: 2.2.0
  flutter_colorpicker: ^1.0.3
  socket_io:
  socket_io_client:
  flutter_acpcore: ^2.0.1
  flutter_acpanalytics: ^2.0.1
  flutter_assurance: ^2.0.1
  get: ^4.6.5
  google_fonts: ^4.0.3
  auto_size_text: ^3.0.0
  flutter_advanced_switch: ^3.0.1
  dots_indicator: ^2.1.0
#  razorpay_flutter:
  timezone: ^0.9.1
  flutter_archive: ^5.0.0
  syncfusion_flutter_charts:
  animated_text_kit:
  validators:
  url_launcher: ^6.1.7
  archive: ^3.3.6
  clevertap_plugin: ^1.6.0
  flutter_styled_toast: ^2.1.3
  clevertap_flutter: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2

dependency_overrides:
  firebase_core_platform_interface: 4.5.3

flutter:
  uses-material-design: true
#  plugin:
#    platforms:
#      android:
#        package: com.clevertap.clevertap_plugin
#        pluginClass: CleverTapPlugin
#      ios:
#        pluginClass: CleverTapPlugin

  assets:
    - assets/images/logo/
    - assets/images/icons/
    - assets/animations/
    - assets/images/
    - assets/appImages/
    - assets/appImages/portfolio/
    - assets/appImages/more/
    - assets/appImages/basket/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Italic.ttf
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

